# Generated by Django 2.1.7 on 2019-12-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreO', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeReparto', models.DateTimeField(blank=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Camion')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Objeto')),
            ],
        ),
    ]
